### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by bmcfee** [dhuppenkothen/entrofy#20]
ConfigParser seems to be causing some trouble.

**Comment by rgaiacs** [comment]
~~~
diff --git a/app/server.py b/app/server.py
index 65dcbfa..6c9196b 100755
--- a/app/server.py
+++ b/app/server.py
@@ -5,7 +5,7 @@ from __future__ import print_function
 import argparse
 from flask import Flask, request, redirect, url_for, render_template, Response
 from werkzeug import secure_filename
-import ConfigParser
+import configparser
 import os
 import re
 import sys
@@ -19,7 +19,7 @@ app = Flask(__name__)
 app.config.from_object(__name__)
 
 def load_config(server_ini):
-    P = ConfigParser.RawConfigParser()
+    P = configparser.RawConfigParser()
 
     P.opionxform = str
     P.read(server_ini)
@@ -28,8 +28,8 @@ def load_config(server_ini):
     for section in P.sections():
         CFG[section] = dict(P.items(section))
 
-    for (k, v) in CFG['server'].iteritems():
-        app.config[k] = v
+    for key in CFG['server']:
+        app.config[key] = CFG['server'][key]
     return CFG
~~~

enable me to run entrofy with Python 3 but I ended up with https://github.com/dhuppenkothen/entrofy/issues/42 which I don't know if is related with my changes.

We could use http://python3porting.com/noconv.html#import-errors to provide compatibility with Python 2.

**Comment by dhuppenkothen** [comment]
I think I'd like to support Python2 a little while longer (a recent informal survey shows that ~70% or so of researchers in my field are still on Python2), so doing the import with an if-statement like the link you posted suggests sounds like a good option. 

In general the flask app needs a lot of work in order to be used reliably. I think #42 stems from the fact that it uses an old implementation of Entrofy in `app/entrofy.py`. We need to port it over to use the code in `entrofy/core.py`, but haven't actually done that yet because the Python implementation has been our priority over the flask app.

**Comment by bmcfee** [comment]
> so doing the import with an if-statement like the link you posted suggests sounds like a good option.

Does [six](https://pythonhosted.org/six/) automate the import rename for this package under `six.moves`?  In general, six is my preferred option for supporting old python versions.
